version: '3.8'

services:
  spring-boot-app:
    build: .
    container_name: ticket-system-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@localhost:1521:XE
      - SPRING_DATASOURCE_USERNAME=itsupport
      - SPRING_DATASOURCE_PASSWORD=itsupport123
    ports:
      - "8080:8080"
