version: '3.8'

services:
  db:
    image: gvenzl/oracle-xe:latest
    restart: always
    environment:
      ORACLE_PASSWORD: password
      ORACLE_DATABASE: XEPDB1
    ports:
      - "1521:1521"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: ITSUPPORT
      SPRING_DATASOURCE_PASSWORD: password
